/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as MainRouteImport } from './routes/main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStatsRouteImport } from './routes/_layout/stats'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLeaderboardRouteImport } from './routes/_layout/leaderboard'
import { Route as LayoutDemoRouteImport } from './routes/_layout/demo'
import { Route as LayoutChallengesRouteImport } from './routes/_layout/challenges'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as LayoutChallengesChallengeIdRouteImport } from './routes/_layout/challenges.$challengeId'
import { Route as LayoutAgentsAgentIdRouteImport } from './routes/_layout/agents.$agentId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStatsRoute = LayoutStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaderboardRoute = LayoutLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoRoute = LayoutDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChallengesRoute = LayoutChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutChallengesChallengeIdRoute =
  LayoutChallengesChallengeIdRouteImport.update({
    id: '/$challengeId',
    path: '/$challengeId',
    getParentRoute: () => LayoutChallengesRoute,
  } as any)
const LayoutAgentsAgentIdRoute = LayoutAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => LayoutAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/arena': typeof ArenaRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/sign-up': typeof SignUpRoute
  '/agents': typeof LayoutAgentsRouteWithChildren
  '/challenges': typeof LayoutChallengesRouteWithChildren
  '/demo': typeof LayoutDemoRoute
  '/leaderboard': typeof LayoutLeaderboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/stats': typeof LayoutStatsRoute
  '/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/challenges/$challengeId': typeof LayoutChallengesChallengeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/arena': typeof ArenaRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/sign-up': typeof SignUpRoute
  '/agents': typeof LayoutAgentsRouteWithChildren
  '/challenges': typeof LayoutChallengesRouteWithChildren
  '/demo': typeof LayoutDemoRoute
  '/leaderboard': typeof LayoutLeaderboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/stats': typeof LayoutStatsRoute
  '/': typeof LayoutIndexRoute
  '/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/challenges/$challengeId': typeof LayoutChallengesChallengeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/arena': typeof ArenaRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/sign-up': typeof SignUpRoute
  '/_layout/agents': typeof LayoutAgentsRouteWithChildren
  '/_layout/challenges': typeof LayoutChallengesRouteWithChildren
  '/_layout/demo': typeof LayoutDemoRoute
  '/_layout/leaderboard': typeof LayoutLeaderboardRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/stats': typeof LayoutStatsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/_layout/challenges/$challengeId': typeof LayoutChallengesChallengeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/login'
    | '/main'
    | '/sign-up'
    | '/agents'
    | '/challenges'
    | '/demo'
    | '/leaderboard'
    | '/settings'
    | '/stats'
    | '/agents/$agentId'
    | '/challenges/$challengeId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/arena'
    | '/login'
    | '/main'
    | '/sign-up'
    | '/agents'
    | '/challenges'
    | '/demo'
    | '/leaderboard'
    | '/settings'
    | '/stats'
    | '/'
    | '/agents/$agentId'
    | '/challenges/$challengeId'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/_layout'
    | '/arena'
    | '/login'
    | '/main'
    | '/sign-up'
    | '/_layout/agents'
    | '/_layout/challenges'
    | '/_layout/demo'
    | '/_layout/leaderboard'
    | '/_layout/settings'
    | '/_layout/stats'
    | '/_layout/'
    | '/_layout/agents/$agentId'
    | '/_layout/challenges/$challengeId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ArenaRoute: typeof ArenaRoute
  LoginRoute: typeof LoginRoute
  MainRoute: typeof MainRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stats': {
      id: '/_layout/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof LayoutStatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leaderboard': {
      id: '/_layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LayoutLeaderboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo': {
      id: '/_layout/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof LayoutDemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/challenges': {
      id: '/_layout/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof LayoutChallengesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/challenges/$challengeId': {
      id: '/_layout/challenges/$challengeId'
      path: '/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof LayoutChallengesChallengeIdRouteImport
      parentRoute: typeof LayoutChallengesRoute
    }
    '/_layout/agents/$agentId': {
      id: '/_layout/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof LayoutAgentsAgentIdRouteImport
      parentRoute: typeof LayoutAgentsRoute
    }
  }
}

interface LayoutAgentsRouteChildren {
  LayoutAgentsAgentIdRoute: typeof LayoutAgentsAgentIdRoute
}

const LayoutAgentsRouteChildren: LayoutAgentsRouteChildren = {
  LayoutAgentsAgentIdRoute: LayoutAgentsAgentIdRoute,
}

const LayoutAgentsRouteWithChildren = LayoutAgentsRoute._addFileChildren(
  LayoutAgentsRouteChildren,
)

interface LayoutChallengesRouteChildren {
  LayoutChallengesChallengeIdRoute: typeof LayoutChallengesChallengeIdRoute
}

const LayoutChallengesRouteChildren: LayoutChallengesRouteChildren = {
  LayoutChallengesChallengeIdRoute: LayoutChallengesChallengeIdRoute,
}

const LayoutChallengesRouteWithChildren =
  LayoutChallengesRoute._addFileChildren(LayoutChallengesRouteChildren)

interface LayoutRouteChildren {
  LayoutAgentsRoute: typeof LayoutAgentsRouteWithChildren
  LayoutChallengesRoute: typeof LayoutChallengesRouteWithChildren
  LayoutDemoRoute: typeof LayoutDemoRoute
  LayoutLeaderboardRoute: typeof LayoutLeaderboardRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStatsRoute: typeof LayoutStatsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAgentsRoute: LayoutAgentsRouteWithChildren,
  LayoutChallengesRoute: LayoutChallengesRouteWithChildren,
  LayoutDemoRoute: LayoutDemoRoute,
  LayoutLeaderboardRoute: LayoutLeaderboardRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStatsRoute: LayoutStatsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ArenaRoute: ArenaRoute,
  LoginRoute: LoginRoute,
  MainRoute: MainRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
