export const agentTrustAbi = [
  {
    type: "function",
    name: "registerAgent",
    inputs: [
      { name: "agentId", type: "bytes32" },
      { name: "name", type: "string" },
      { name: "capabilities", type: "string[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createChallenge",
    inputs: [
      { name: "agentId", type: "bytes32" },
      { name: "capability", type: "string" },
      { name: "prompt", type: "string" },
      { name: "answerHash", type: "bytes32" },
      { name: "durationSeconds", type: "uint256" },
    ],
    outputs: [{ name: "challengeId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitResult",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "resultHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revealAnswer",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "answer", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAgentProfile",
    inputs: [{ name: "agentId", type: "bytes32" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "name", type: "string" },
      { name: "capabilities", type: "string[]" },
      { name: "totalChallenges", type: "uint256" },
      { name: "passedChallenges", type: "uint256" },
      { name: "failedChallenges", type: "uint256" },
      { name: "registeredAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgentCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgentIdByIndex",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "challengeCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "challenges",
    inputs: [{ type: "uint256" }],
    outputs: [
      { name: "creator", type: "address" },
      { name: "agentId", type: "bytes32" },
      { name: "capability", type: "string" },
      { name: "prompt", type: "string" },
      { name: "answerHash", type: "bytes32" },
      { name: "submittedHash", type: "bytes32" },
      { name: "status", type: "uint8" },
      { name: "createdAt", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "passed", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AgentRegistered",
    inputs: [
      { name: "agentId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeCreated",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "agentId", type: "bytes32", indexed: true },
      { name: "capability", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeSubmitted",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "agentId", type: "bytes32", indexed: true },
    ],
  },
  {
    type: "event",
    name: "ChallengeRevealed",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "agentId", type: "bytes32", indexed: true },
      { name: "passed", type: "bool", indexed: false },
    ],
  },
] as const;
